### ISSUE TITLE
react-orbit npm package doesn't contain anything

### ISSUE THREAD

**Issue by inspiraluna** [revolunet/react-orbitdb#4]
I wanted to ```yarn add react-orbitdb``` into a brand new react project but when I looked into node_modules/react-orbitdb it is empty. Also the hooks etc. are missing. the dependencies (ipfs, orbitdb,etc.) seem to be installing. So far I didn't have time to look into the reason.

**Comment by revolunet** [comment]
Thanks for reporting @inspiraluna , this should be fixed (was an issue with the GH publish workflow i guess)

**Comment by NiKrause** [comment]
btw. I made a fork from your awesome lib and updated it to the latest versions. It works with webpack etc. 
But I am still not finished and not good for a PR yet. But if you like you can have a look. It still needs some clean up. 
https://github.com/DecentraSol/react-orbitdb
